services:
  simple-file-server:
    build: .
    container_name: mfx-file-server
    env_file: .env
    environment:
      - LOG_LEVEL=debug
      - LOCATION_BASE_URL=https://sfs.$DOMAIN
      - DATA_DIR=/data
      # - WRITE_SHARED_KEY=abc
      # - READ_SHARED_KEY=123
    volumes:
      - ./test_file.txt:/seed/test_file.txt
      # consolidated seed files volume bind
      - ./files:/seed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simple-file-server.rule=Host(`sfs.$DOMAIN`)"
      - "traefik.http.routers.simple-file-server.entrypoints=websecure"
      - "traefik.http.routers.simple-file-server.tls.certresolver=myresolver"
      - "traefik.http.services.simple-file-server.loadbalancer.server.port=4000"
    restart: unless-stopped
    networks:
      - reverse-proxy-public