services:
  simple-file-server:
    build: .
    image: flaviostutz/simple-file-server
    ports:
      - "4000:4000"
    volumes:
      - ./test_file:/data/test_file
    environment:
      - WRITE_SHARED_KEY=
      - READ_SHARED_KEY=
      - LOCATION_BASE_URL=http://p1-a.local.timothyholmes.com.au:4000
      - LOG_LEVEL=debug
      - DATA_DIR=/data
